<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ann Brennan - HW 3 - Beer Markets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ann Brennan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../danl_320_brennan_ann_project.html" rel="" target="">
 <span class="menu-text">DANL320 Final Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-final-projects" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Final Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-final-projects">    
        <li>
    <a class="dropdown-item" href="../../project.html" rel="" target="">
 <span class="dropdown-text">DANL200</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../project-210.html" rel="" target="">
 <span class="dropdown-text">DANL210</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../blog-listing.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../danl_proj_nba.html" rel="" target="">
 <span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-python-data-analysis" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Python Data Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-python-data-analysis">    
        <li>
    <a class="dropdown-item" href="../../pandas_basics.html" rel="" target="">
 <span class="dropdown-text">Pandas Basics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../seaborn_basics.html" rel="" target="">
 <span class="dropdown-text">Seaborn Basics</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <div class="quarto-navbar-tools ms-auto">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">HW 3 - Beer Markets</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>In this post, we will be exploring beer pricing by analyzing the DataFrame “Beer Markets”. This DataFrame contains information about beer purchase details and household characteristics. We will analyze how these factors, such as household size, type of beer container, and household income impact the price of beer (per fluid ounce).</p>
<section id="loading-packages-and-settings" class="level2">
<h2 class="anchored" data-anchor-id="loading-packages-and-settings">Loading Packages and Settings</h2>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tabulate <span class="im">import</span> tabulate  <span class="co"># for table summary</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm  <span class="co"># for lowess smoothing</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> rand, col, <span class="bu">pow</span>, mean, avg, when, log, sqrt, exp</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> VectorAssembler</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression, GeneralizedLinearRegression</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> BinaryClassificationEvaluator</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.master(<span class="st">"local[*]"</span>).getOrCreate()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="udfs" class="level2">
<h2 class="anchored" data-anchor-id="udfs">UDFs</h2>
<p>We will be using a variety of User Defined Functions (UDFs) in order to perform functions necessary for our Linear Regression Models. We will define our UDFs before we begin.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_dummy_variables(var_name, reference_level, category_order<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Creates dummy variables for the specified column in the global DataFrames dtrain and dtest.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Allows manual setting of category order.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">        var_name (str): The name of the categorical column (e.g., "borough_name").</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">        reference_level (int): Index of the category to be used as the reference (dummy omitted).</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">        category_order (list, optional): List of categories in the desired order. If None, categories are sorted.</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">        dummy_cols (list): List of dummy column names excluding the reference category.</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">        ref_category (str): The category chosen as the reference.</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">global</span> dtrain, dtest</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get distinct categories from the training set.</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    categories <span class="op">=</span> dtrain.select(var_name).distinct().rdd.flatMap(<span class="kw">lambda</span> x: x).collect()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert booleans to strings if present.</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    categories <span class="op">=</span> [<span class="bu">str</span>(c) <span class="cf">if</span> <span class="bu">isinstance</span>(c, <span class="bu">bool</span>) <span class="cf">else</span> c <span class="cf">for</span> c <span class="kw">in</span> categories]</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Use manual category order if provided; otherwise, sort categories.</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> category_order:</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Ensure all categories are present in the user-defined order</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        missing <span class="op">=</span> <span class="bu">set</span>(categories) <span class="op">-</span> <span class="bu">set</span>(category_order)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> missing:</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"These categories are missing from your custom order: </span><span class="sc">{</span>missing<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        categories <span class="op">=</span> category_order</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        categories <span class="op">=</span> <span class="bu">sorted</span>(categories)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Validate reference_level</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> reference_level <span class="op">&lt;</span> <span class="dv">0</span> <span class="kw">or</span> reference_level <span class="op">&gt;=</span> <span class="bu">len</span>(categories):</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="ss">f"reference_level must be between 0 and </span><span class="sc">{</span><span class="bu">len</span>(categories) <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define the reference category</span></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    ref_category <span class="op">=</span> categories[reference_level]</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Reference category (dummy omitted):"</span>, ref_category)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create dummy variables for all categories</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> cat <span class="kw">in</span> categories:</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>        dummy_col_name <span class="op">=</span> var_name <span class="op">+</span> <span class="st">"_"</span> <span class="op">+</span> <span class="bu">str</span>(cat).replace(<span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>        dtrain <span class="op">=</span> dtrain.withColumn(dummy_col_name, when(col(var_name) <span class="op">==</span> cat, <span class="dv">1</span>).otherwise(<span class="dv">0</span>))</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>        dtest <span class="op">=</span> dtest.withColumn(dummy_col_name, when(col(var_name) <span class="op">==</span> cat, <span class="dv">1</span>).otherwise(<span class="dv">0</span>))</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># List of dummy columns, excluding the reference category</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>    dummy_cols <span class="op">=</span> [var_name <span class="op">+</span> <span class="st">"_"</span> <span class="op">+</span> <span class="bu">str</span>(cat).replace(<span class="st">" "</span>, <span class="st">"_"</span>) <span class="cf">for</span> cat <span class="kw">in</span> categories <span class="cf">if</span> cat <span class="op">!=</span> ref_category]</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dummy_cols, ref_category</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage without category_order:</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy_cols_year, ref_category_year = add_dummy_variables('year', 0)</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a><span class="co"># Example usage with category_order:</span></span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a><span class="co"># custom_order_wkday = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy_cols_wkday, ref_category_wkday = add_dummy_variables('wkday', reference_level=0, category_order = custom_order_wkday)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> regression_table(model, assembler):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Creates a formatted regression table from a fitted LinearRegression model and its VectorAssembler,</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">    and inserts a dashed horizontal line after the Intercept row. The table includes separate columns</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">    for the 95% confidence interval lower and upper bounds for each coefficient (computed at the 5% significance level)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">    and an "Observations" row (using model.summary.numInstances) above the R² row.</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">    The RMSE row is placed as the last row.</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">    The columns are ordered as:</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">        Metric | Value | Significance | Std. Error | p-value | 95% CI Lower | 95% CI Upper</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">    For the "Value", "Std. Error", "95% CI Lower", and "95% CI Upper" columns, commas are inserted every three digits,</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">    with 3 decimal places (except for Observations which is formatted as an integer with commas).</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">        model: A fitted LinearRegression model (with a .summary attribute).</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">        assembler: The VectorAssembler used to assemble the features for the model.</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co">        A formatted string containing the regression table.</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract coefficients and standard errors as NumPy arrays</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    coeffs <span class="op">=</span> model.coefficients.toArray()</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    std_errors_all <span class="op">=</span> np.array(model.summary.coefficientStandardErrors)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if the intercept's standard error is included (one extra element)</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(std_errors_all) <span class="op">==</span> <span class="bu">len</span>(coeffs) <span class="op">+</span> <span class="dv">1</span>:</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> std_errors_all[<span class="dv">0</span>]</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        std_errors <span class="op">=</span> std_errors_all[<span class="dv">1</span>:]</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> <span class="va">None</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>        std_errors <span class="op">=</span> std_errors_all</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute t-statistics for feature coefficients (t = beta / SE(beta))</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="co"># t_stats = coeffs / std_errors</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    t_stats <span class="op">=</span> model.summary.tValues</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Degrees of freedom: number of instances minus number of predictors minus 1 (for intercept)</span></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> model.summary.numInstances <span class="op">-</span> <span class="bu">len</span>(coeffs) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the t-critical value for a 95% confidence interval (two-tailed, 5% significance)</span></span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>    t_critical <span class="op">=</span> stats.t.ppf(<span class="fl">0.975</span>, df)</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute two-tailed p-values for each feature coefficient</span></span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># p_values = [2 * (1 - stats.t.cdf(np.abs(t), df)) for t in t_stats]</span></span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>    p_values <span class="op">=</span> model.summary.pValues</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Function to assign significance stars based on p-value</span></span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> significance_stars(p):</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.01</span>:</span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"***"</span></span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> p <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"**"</span></span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> p <span class="op">&lt;</span> <span class="fl">0.1</span>:</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">"*"</span></span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="st">""</span></span>
<span id="cb3-59"><a href="#cb3-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-60"><a href="#cb3-60" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Build the table rows.</span></span>
<span id="cb3-61"><a href="#cb3-61" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Order: Metric, Value, Significance, Std. Error, p-value, 95% CI Lower, 95% CI Upper.</span></span>
<span id="cb3-62"><a href="#cb3-62" aria-hidden="true" tabindex="-1"></a>    table <span class="op">=</span> []</span>
<span id="cb3-63"><a href="#cb3-63" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> feature, beta, se, p <span class="kw">in</span> <span class="bu">zip</span>(assembler.getInputCols(), coeffs, std_errors, p_values):</span>
<span id="cb3-64"><a href="#cb3-64" aria-hidden="true" tabindex="-1"></a>        ci_lower <span class="op">=</span> beta <span class="op">-</span> t_critical <span class="op">*</span> se</span>
<span id="cb3-65"><a href="#cb3-65" aria-hidden="true" tabindex="-1"></a>        ci_upper <span class="op">=</span> beta <span class="op">+</span> t_critical <span class="op">*</span> se</span>
<span id="cb3-66"><a href="#cb3-66" aria-hidden="true" tabindex="-1"></a>        table.append([</span>
<span id="cb3-67"><a href="#cb3-67" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Beta: "</span> <span class="op">+</span> feature,       <span class="co"># Metric name</span></span>
<span id="cb3-68"><a href="#cb3-68" aria-hidden="true" tabindex="-1"></a>            beta,                     <span class="co"># Beta estimate (Value)</span></span>
<span id="cb3-69"><a href="#cb3-69" aria-hidden="true" tabindex="-1"></a>            significance_stars(p),    <span class="co"># Significance stars</span></span>
<span id="cb3-70"><a href="#cb3-70" aria-hidden="true" tabindex="-1"></a>            se,                       <span class="co"># Standard error</span></span>
<span id="cb3-71"><a href="#cb3-71" aria-hidden="true" tabindex="-1"></a>            p,                        <span class="co"># p-value</span></span>
<span id="cb3-72"><a href="#cb3-72" aria-hidden="true" tabindex="-1"></a>            ci_lower,                 <span class="co"># 95% CI lower bound</span></span>
<span id="cb3-73"><a href="#cb3-73" aria-hidden="true" tabindex="-1"></a>            ci_upper                  <span class="co"># 95% CI upper bound</span></span>
<span id="cb3-74"><a href="#cb3-74" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb3-75"><a href="#cb3-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-76"><a href="#cb3-76" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute and add the intercept row with its SE, p-value, significance, and CI (if available)</span></span>
<span id="cb3-77"><a href="#cb3-77" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> intercept_se <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb3-78"><a href="#cb3-78" aria-hidden="true" tabindex="-1"></a>        intercept_t <span class="op">=</span> model.intercept <span class="op">/</span> intercept_se</span>
<span id="cb3-79"><a href="#cb3-79" aria-hidden="true" tabindex="-1"></a>        intercept_p <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> stats.t.cdf(np.<span class="bu">abs</span>(intercept_t), df))</span>
<span id="cb3-80"><a href="#cb3-80" aria-hidden="true" tabindex="-1"></a>        intercept_sig <span class="op">=</span> significance_stars(intercept_p)</span>
<span id="cb3-81"><a href="#cb3-81" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower <span class="op">=</span> model.intercept <span class="op">-</span> t_critical <span class="op">*</span> intercept_se</span>
<span id="cb3-82"><a href="#cb3-82" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper <span class="op">=</span> model.intercept <span class="op">+</span> t_critical <span class="op">*</span> intercept_se</span>
<span id="cb3-83"><a href="#cb3-83" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb3-84"><a href="#cb3-84" aria-hidden="true" tabindex="-1"></a>        intercept_se <span class="op">=</span> <span class="st">""</span></span>
<span id="cb3-85"><a href="#cb3-85" aria-hidden="true" tabindex="-1"></a>        intercept_p <span class="op">=</span> <span class="st">""</span></span>
<span id="cb3-86"><a href="#cb3-86" aria-hidden="true" tabindex="-1"></a>        intercept_sig <span class="op">=</span> <span class="st">""</span></span>
<span id="cb3-87"><a href="#cb3-87" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower <span class="op">=</span> <span class="st">""</span></span>
<span id="cb3-88"><a href="#cb3-88" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper <span class="op">=</span> <span class="st">""</span></span>
<span id="cb3-89"><a href="#cb3-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-90"><a href="#cb3-90" aria-hidden="true" tabindex="-1"></a>    table.append([</span>
<span id="cb3-91"><a href="#cb3-91" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Intercept"</span>,</span>
<span id="cb3-92"><a href="#cb3-92" aria-hidden="true" tabindex="-1"></a>        model.intercept,</span>
<span id="cb3-93"><a href="#cb3-93" aria-hidden="true" tabindex="-1"></a>        intercept_sig,</span>
<span id="cb3-94"><a href="#cb3-94" aria-hidden="true" tabindex="-1"></a>        intercept_se,</span>
<span id="cb3-95"><a href="#cb3-95" aria-hidden="true" tabindex="-1"></a>        intercept_p,</span>
<span id="cb3-96"><a href="#cb3-96" aria-hidden="true" tabindex="-1"></a>        ci_intercept_lower,</span>
<span id="cb3-97"><a href="#cb3-97" aria-hidden="true" tabindex="-1"></a>        ci_intercept_upper</span>
<span id="cb3-98"><a href="#cb3-98" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb3-99"><a href="#cb3-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-100"><a href="#cb3-100" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Append overall model metrics:</span></span>
<span id="cb3-101"><a href="#cb3-101" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Insert an Observations row using model.summary.numInstances,</span></span>
<span id="cb3-102"><a href="#cb3-102" aria-hidden="true" tabindex="-1"></a>    <span class="co"># then an R² row, and finally the RMSE row as the last row.</span></span>
<span id="cb3-103"><a href="#cb3-103" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"Observations"</span>, model.summary.numInstances, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb3-104"><a href="#cb3-104" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"R²"</span>, model.summary.r2, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb3-105"><a href="#cb3-105" aria-hidden="true" tabindex="-1"></a>    table.append([<span class="st">"RMSE"</span>, model.summary.rootMeanSquaredError, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>, <span class="st">""</span>])</span>
<span id="cb3-106"><a href="#cb3-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-107"><a href="#cb3-107" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Format the table.</span></span>
<span id="cb3-108"><a href="#cb3-108" aria-hidden="true" tabindex="-1"></a>    <span class="co"># For the "Value" (index 1), "Std. Error" (index 3), "95% CI Lower" (index 5), and "95% CI Upper" (index 6) columns,</span></span>
<span id="cb3-109"><a href="#cb3-109" aria-hidden="true" tabindex="-1"></a>    <span class="co"># format with commas and 3 decimal places, except for Observations which should be an integer with commas.</span></span>
<span id="cb3-110"><a href="#cb3-110" aria-hidden="true" tabindex="-1"></a>    <span class="co"># For the p-value (index 4), format to 3 decimal places.</span></span>
<span id="cb3-111"><a href="#cb3-111" aria-hidden="true" tabindex="-1"></a>    formatted_table <span class="op">=</span> []</span>
<span id="cb3-112"><a href="#cb3-112" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> row <span class="kw">in</span> table:</span>
<span id="cb3-113"><a href="#cb3-113" aria-hidden="true" tabindex="-1"></a>        formatted_row <span class="op">=</span> []</span>
<span id="cb3-114"><a href="#cb3-114" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, item <span class="kw">in</span> <span class="bu">enumerate</span>(row):</span>
<span id="cb3-115"><a href="#cb3-115" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> row[<span class="dv">0</span>] <span class="op">==</span> <span class="st">"Observations"</span> <span class="kw">and</span> i <span class="op">==</span> <span class="dv">1</span> <span class="kw">and</span> <span class="bu">isinstance</span>(item, (<span class="bu">int</span>, <span class="bu">float</span>, np.floating)) <span class="kw">and</span> item <span class="op">!=</span> <span class="st">""</span>:</span>
<span id="cb3-116"><a href="#cb3-116" aria-hidden="true" tabindex="-1"></a>                <span class="co"># Format Observations as integer with commas, no decimals.</span></span>
<span id="cb3-117"><a href="#cb3-117" aria-hidden="true" tabindex="-1"></a>                formatted_row.append(<span class="ss">f"</span><span class="sc">{</span><span class="bu">int</span>(item)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb3-118"><a href="#cb3-118" aria-hidden="true" tabindex="-1"></a>            <span class="cf">elif</span> <span class="bu">isinstance</span>(item, (<span class="bu">int</span>, <span class="bu">float</span>, np.floating)) <span class="kw">and</span> item <span class="op">!=</span> <span class="st">""</span>:</span>
<span id="cb3-119"><a href="#cb3-119" aria-hidden="true" tabindex="-1"></a>                <span class="cf">if</span> i <span class="kw">in</span> [<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>]:</span>
<span id="cb3-120"><a href="#cb3-120" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:,</span><span class="fl">.3</span><span class="er">f</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-121"><a href="#cb3-121" aria-hidden="true" tabindex="-1"></a>                <span class="cf">elif</span> i <span class="op">==</span> <span class="dv">4</span>:</span>
<span id="cb3-122"><a href="#cb3-122" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-123"><a href="#cb3-123" aria-hidden="true" tabindex="-1"></a>                <span class="cf">else</span>:</span>
<span id="cb3-124"><a href="#cb3-124" aria-hidden="true" tabindex="-1"></a>                    formatted_row.append(<span class="ss">f"</span><span class="sc">{</span>item<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-125"><a href="#cb3-125" aria-hidden="true" tabindex="-1"></a>            <span class="cf">else</span>:</span>
<span id="cb3-126"><a href="#cb3-126" aria-hidden="true" tabindex="-1"></a>                formatted_row.append(item)</span>
<span id="cb3-127"><a href="#cb3-127" aria-hidden="true" tabindex="-1"></a>        formatted_table.append(formatted_row)</span>
<span id="cb3-128"><a href="#cb3-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-129"><a href="#cb3-129" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate the table string using tabulate.</span></span>
<span id="cb3-130"><a href="#cb3-130" aria-hidden="true" tabindex="-1"></a>    table_str <span class="op">=</span> tabulate(</span>
<span id="cb3-131"><a href="#cb3-131" aria-hidden="true" tabindex="-1"></a>        formatted_table,</span>
<span id="cb3-132"><a href="#cb3-132" aria-hidden="true" tabindex="-1"></a>        headers<span class="op">=</span>[<span class="st">"Metric"</span>, <span class="st">"Value"</span>, <span class="st">"Sig."</span>, <span class="st">"Std. Error"</span>, <span class="st">"p-value"</span>, <span class="st">"95% CI Lower"</span>, <span class="st">"95% CI Upper"</span>],</span>
<span id="cb3-133"><a href="#cb3-133" aria-hidden="true" tabindex="-1"></a>        tablefmt<span class="op">=</span><span class="st">"pretty"</span>,</span>
<span id="cb3-134"><a href="#cb3-134" aria-hidden="true" tabindex="-1"></a>        colalign<span class="op">=</span>(<span class="st">"left"</span>, <span class="st">"right"</span>, <span class="st">"center"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>)</span>
<span id="cb3-135"><a href="#cb3-135" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-136"><a href="#cb3-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-137"><a href="#cb3-137" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Insert a dashed line after the Intercept row for clarity.</span></span>
<span id="cb3-138"><a href="#cb3-138" aria-hidden="true" tabindex="-1"></a>    lines <span class="op">=</span> table_str.split(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb3-139"><a href="#cb3-139" aria-hidden="true" tabindex="-1"></a>    dash_line <span class="op">=</span> <span class="st">'-'</span> <span class="op">*</span> <span class="bu">len</span>(lines[<span class="dv">0</span>])</span>
<span id="cb3-140"><a href="#cb3-140" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, line <span class="kw">in</span> <span class="bu">enumerate</span>(lines):</span>
<span id="cb3-141"><a href="#cb3-141" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="st">"Intercept"</span> <span class="kw">in</span> line <span class="kw">and</span> <span class="kw">not</span> line.strip().startswith(<span class="st">'+'</span>):</span>
<span id="cb3-142"><a href="#cb3-142" aria-hidden="true" tabindex="-1"></a>            lines.insert(i<span class="op">+</span><span class="dv">1</span>, dash_line)</span>
<span id="cb3-143"><a href="#cb3-143" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb3-144"><a href="#cb3-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-145"><a href="#cb3-145" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(lines)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> add_interaction_terms(var_list1, var_list2, var_list3<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Creates interaction term columns in the global DataFrames dtrain and dtest.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">    For two sets of variable names (which may represent categorical (dummy) or continuous variables),</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">    this function creates two-way interactions by multiplying each variable in var_list1 with each</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">    variable in var_list2.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Optionally, if a third list of variable names (var_list3) is provided, the function also creates</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">    three-way interactions among each variable in var_list1, each variable in var_list2, and each variable</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co">    in var_list3.</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">        var_list1 (list): List of column names for the first set of variables.</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co">        var_list2 (list): List of column names for the second set of variables.</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co">        var_list3 (list, optional): List of column names for the third set of variables for three-way interactions.</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co">        A flat list of new interaction column names.</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="kw">global</span> dtrain, dtest</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    interaction_cols <span class="op">=</span> []</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create two-way interactions between var_list1 and var_list2.</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> var1 <span class="kw">in</span> var_list1:</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> var2 <span class="kw">in</span> var_list2:</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>            col_name <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>var1<span class="sc">}</span><span class="ss">_*_</span><span class="sc">{</span>var2<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>            dtrain <span class="op">=</span> dtrain.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var2).cast(<span class="st">"double"</span>))</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>            dtest <span class="op">=</span> dtest.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var2).cast(<span class="st">"double"</span>))</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>            interaction_cols.append(col_name)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create two-way interactions between var_list1 and var_list3.</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> var_list3 <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span> var1 <span class="kw">in</span> var_list1:</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>          <span class="cf">for</span> var3 <span class="kw">in</span> var_list3:</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>              col_name <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>var1<span class="sc">}</span><span class="ss">_*_</span><span class="sc">{</span>var3<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>              dtrain <span class="op">=</span> dtrain.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>              dtest <span class="op">=</span> dtest.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>              interaction_cols.append(col_name)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create two-way interactions between var_list2 and var_list3.</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> var_list3 <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>      <span class="cf">for</span> var2 <span class="kw">in</span> var_list2:</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>          <span class="cf">for</span> var3 <span class="kw">in</span> var_list3:</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>              col_name <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>var2<span class="sc">}</span><span class="ss">_*_</span><span class="sc">{</span>var3<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>              dtrain <span class="op">=</span> dtrain.withColumn(col_name, col(var2).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>              dtest <span class="op">=</span> dtest.withColumn(col_name, col(var2).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>              interaction_cols.append(col_name)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If a third list is provided, create three-way interactions.</span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> var_list3 <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> var1 <span class="kw">in</span> var_list1:</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> var2 <span class="kw">in</span> var_list2:</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>                <span class="cf">for</span> var3 <span class="kw">in</span> var_list3:</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>                    col_name <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>var1<span class="sc">}</span><span class="ss">_*_</span><span class="sc">{</span>var2<span class="sc">}</span><span class="ss">_*_</span><span class="sc">{</span>var3<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>                    dtrain <span class="op">=</span> dtrain.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var2).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>                    dtest <span class="op">=</span> dtest.withColumn(col_name, col(var1).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var2).cast(<span class="st">"double"</span>) <span class="op">*</span> col(var3).cast(<span class="st">"double"</span>))</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>                    interaction_cols.append(col_name)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> interaction_cols</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a> <span class="co"># Example</span></span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a> <span class="co"># interaction_cols_brand_price = add_interaction_terms(dummy_cols_brand, ['log_price'])</span></span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a> <span class="co"># interaction_cols_brand_ad_price = add_interaction_terms(dummy_cols_brand, dummy_cols_ad, ['log_price'])</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-dataframe---beer-markets" class="level2">
<h2 class="anchored" data-anchor-id="loading-dataframe---beer-markets">Loading DataFrame - Beer Markets</h2>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>beer_markets <span class="op">=</span> pd.read_csv(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">'https://bcdanl.github.io/data/beer_markets_all_cleaned.csv'</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="filtering-dataframe" class="level2">
<h2 class="anchored" data-anchor-id="filtering-dataframe">Filtering DataFrame</h2>
<p>We will be focusing on observations that are either a can or non-refillable bottle in the beer_markets DataFrame. Additionally, we will be using the log of beer volume as one of our predictors.</p>
<div class="cell" data-outputid="c328d441-13d9-4df7-94f2-0519b209dc5d" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>beer_df <span class="op">=</span> beer_markets.loc[</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  (beer_markets[<span class="st">'container'</span>] <span class="op">==</span> <span class="st">'CAN'</span>) <span class="op">|</span> (beer_markets[<span class="st">'container'</span>] <span class="op">==</span> <span class="st">'NON REFILLABLE BOTTLE'</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>beer_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">

  <div id="df-387a278f-cc8f-4f70-9f75-460e7a0c3253" class="colab-df-container">
    <div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">household</th>
<th data-quarto-table-cell-role="th">X_purchase_desc</th>
<th data-quarto-table-cell-role="th">quantity</th>
<th data-quarto-table-cell-role="th">brand</th>
<th data-quarto-table-cell-role="th">dollar_spent</th>
<th data-quarto-table-cell-role="th">beer_floz</th>
<th data-quarto-table-cell-role="th">price_floz</th>
<th data-quarto-table-cell-role="th">container</th>
<th data-quarto-table-cell-role="th">promo</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">employment</th>
<th data-quarto-table-cell-role="th">degree</th>
<th data-quarto-table-cell-role="th">occupation</th>
<th data-quarto-table-cell-role="th">ethnic</th>
<th data-quarto-table-cell-role="th">microwave</th>
<th data-quarto-table-cell-role="th">dishwasher</th>
<th data-quarto-table-cell-role="th">tvcable</th>
<th data-quarto-table-cell-role="th">singlefamilyhome</th>
<th data-quarto-table-cell-role="th">npeople</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2000946</td>
<td>BUD LT BR CN 12P</td>
<td>1</td>
<td>BUD_LIGHT</td>
<td>8.14</td>
<td>144.0</td>
<td>0.056528</td>
<td>CAN</td>
<td>False</td>
<td>CENTRAL</td>
<td>...</td>
<td>50+</td>
<td>none</td>
<td>Grad</td>
<td>none/retired/student</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>premium</td>
<td>False</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2003036</td>
<td>BUD LT BR CN 24P</td>
<td>1</td>
<td>BUD_LIGHT</td>
<td>17.48</td>
<td>288.0</td>
<td>0.060694</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>College</td>
<td>clerical/sales/service</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>basic</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2003036</td>
<td>BUD LT BR CN 24P</td>
<td>2</td>
<td>BUD_LIGHT</td>
<td>33.92</td>
<td>576.0</td>
<td>0.058889</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>College</td>
<td>clerical/sales/service</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>basic</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2003036</td>
<td>BUD LT BR CN 30P</td>
<td>2</td>
<td>BUD_LIGHT</td>
<td>34.74</td>
<td>720.0</td>
<td>0.048250</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>College</td>
<td>clerical/sales/service</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>basic</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2003036</td>
<td>BUD LT BR CN 36P</td>
<td>2</td>
<td>BUD_LIGHT</td>
<td>40.48</td>
<td>864.0</td>
<td>0.046852</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>College</td>
<td>clerical/sales/service</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>basic</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">73110</td>
<td>9158319</td>
<td>NATURAL LT BR CN 24P</td>
<td>1</td>
<td>NATURAL_LIGHT</td>
<td>11.49</td>
<td>288.0</td>
<td>0.039896</td>
<td>CAN</td>
<td>True</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>none</td>
<td>HS</td>
<td>none/retired/student</td>
<td>black</td>
<td>True</td>
<td>True</td>
<td>premium</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">73111</td>
<td>9158319</td>
<td>NATURAL LT BR CN 24P</td>
<td>1</td>
<td>NATURAL_LIGHT</td>
<td>9.97</td>
<td>288.0</td>
<td>0.034618</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>none</td>
<td>HS</td>
<td>none/retired/student</td>
<td>black</td>
<td>True</td>
<td>True</td>
<td>premium</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">73112</td>
<td>9158319</td>
<td>NATURAL LT BR CN 24P</td>
<td>1</td>
<td>NATURAL_LIGHT</td>
<td>9.98</td>
<td>288.0</td>
<td>0.034653</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>none</td>
<td>HS</td>
<td>none/retired/student</td>
<td>black</td>
<td>True</td>
<td>True</td>
<td>premium</td>
<td>True</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">73113</td>
<td>9164033</td>
<td>NATURAL LT BR CN 30P</td>
<td>1</td>
<td>NATURAL_LIGHT</td>
<td>12.98</td>
<td>360.0</td>
<td>0.036056</td>
<td>CAN</td>
<td>False</td>
<td>WEST</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>College</td>
<td>prof</td>
<td>hispanic</td>
<td>True</td>
<td>True</td>
<td>basic</td>
<td>True</td>
<td>5plus</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">73114</td>
<td>9164155</td>
<td>NATURAL LT BR CN 24P</td>
<td>1</td>
<td>NATURAL_LIGHT</td>
<td>13.49</td>
<td>288.0</td>
<td>0.046840</td>
<td>CAN</td>
<td>False</td>
<td>SOUTH</td>
<td>...</td>
<td>50+</td>
<td>full</td>
<td>HS</td>
<td>labor/craft/military/farm</td>
<td>white</td>
<td>True</td>
<td>True</td>
<td>none</td>
<td>True</td>
<td>2</td>
</tr>
</tbody>
</table>


<p>53015 rows × 26 columns</p>
</div>
    <div class="colab-df-buttons">

  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-387a278f-cc8f-4f70-9f75-460e7a0c3253')" title="Convert this dataframe to an interactive table." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"></path>
  </svg>
    </button>

  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-387a278f-cc8f-4f70-9f75-460e7a0c3253 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-387a278f-cc8f-4f70-9f75-460e7a0c3253');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>


<div id="df-289b0547-e87a-46e9-9da9-e298ef67b24d">
  <button class="colab-df-quickchart" onclick="quickchart('df-289b0547-e87a-46e9-9da9-e298ef67b24d')" title="Suggest charts" style="display:none;">

<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <g>
        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"></path>
    </g>
</svg>
  </button>

<style>
  .colab-df-quickchart {
      --bg-color: #E8F0FE;
      --fill-color: #1967D2;
      --hover-bg-color: #E2EBFA;
      --hover-fill-color: #174EA6;
      --disabled-fill-color: #AAA;
      --disabled-bg-color: #DDD;
  }

  [theme=dark] .colab-df-quickchart {
      --bg-color: #3B4455;
      --fill-color: #D2E3FC;
      --hover-bg-color: #434B5C;
      --hover-fill-color: #FFFFFF;
      --disabled-bg-color: #3B4455;
      --disabled-fill-color: #666;
  }

  .colab-df-quickchart {
    background-color: var(--bg-color);
    border: none;
    border-radius: 50%;
    cursor: pointer;
    display: none;
    fill: var(--fill-color);
    height: 32px;
    padding: 0;
    width: 32px;
  }

  .colab-df-quickchart:hover {
    background-color: var(--hover-bg-color);
    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);
    fill: var(--button-hover-fill-color);
  }

  .colab-df-quickchart-complete:disabled,
  .colab-df-quickchart-complete:disabled:hover {
    background-color: var(--disabled-bg-color);
    fill: var(--disabled-fill-color);
    box-shadow: none;
  }

  .colab-df-spinner {
    border: 2px solid var(--fill-color);
    border-color: transparent;
    border-bottom-color: var(--fill-color);
    animation:
      spin 1s steps(1) infinite;
  }

  @keyframes spin {
    0% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
      border-left-color: var(--fill-color);
    }
    20% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    30% {
      border-color: transparent;
      border-left-color: var(--fill-color);
      border-top-color: var(--fill-color);
      border-right-color: var(--fill-color);
    }
    40% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-top-color: var(--fill-color);
    }
    60% {
      border-color: transparent;
      border-right-color: var(--fill-color);
    }
    80% {
      border-color: transparent;
      border-right-color: var(--fill-color);
      border-bottom-color: var(--fill-color);
    }
    90% {
      border-color: transparent;
      border-bottom-color: var(--fill-color);
    }
  }
</style>

  <script>
    async function quickchart(key) {
      const quickchartButtonEl =
        document.querySelector('#' + key + ' button');
      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.
      quickchartButtonEl.classList.add('colab-df-spinner');
      try {
        const charts = await google.colab.kernel.invokeFunction(
            'suggestCharts', [key], {});
      } catch (error) {
        console.error('Error during call to suggestCharts:', error);
      }
      quickchartButtonEl.classList.remove('colab-df-spinner');
      quickchartButtonEl.classList.add('colab-df-quickchart-complete');
    }
    (() => {
      let quickchartButtonEl =
        document.querySelector('#df-289b0547-e87a-46e9-9da9-e298ef67b24d button');
      quickchartButtonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';
    })();
  </script>
</div>

  <div id="id_d1a26783-98ad-4854-98ba-f28d717f9a18">
    <style>
      .colab-df-generate {
        background-color: #E8F0FE;
        border: none;
        border-radius: 50%;
        cursor: pointer;
        display: none;
        fill: #1967D2;
        height: 32px;
        padding: 0 0 0 0;
        width: 32px;
      }

      .colab-df-generate:hover {
        background-color: #E2EBFA;
        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
        fill: #174EA6;
      }

      [theme=dark] .colab-df-generate {
        background-color: #3B4455;
        fill: #D2E3FC;
      }

      [theme=dark] .colab-df-generate:hover {
        background-color: #434B5C;
        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
        fill: #FFFFFF;
      }
    </style>
    <button class="colab-df-generate" onclick="generateWithVariable('beer_df')" title="Generate code using this dataframe." style="display:none;">

  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewbox="0 0 24 24" width="24px">
    <path d="M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z"></path>
  </svg>
    </button>
    <script>
      (() => {
      const buttonEl =
        document.querySelector('#id_d1a26783-98ad-4854-98ba-f28d717f9a18 button.colab-df-generate');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      buttonEl.onclick = () => {
        google.colab.notebook.generateWithVariable('beer_df');
      }
      })();
    </script>
  </div>

    </div>
  </div>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.createDataFrame(beer_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.withColumn(<span class="st">'log_beer_floz'</span>, log(<span class="st">'beer_floz'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.withColumn(<span class="st">'log_price_floz'</span>, log(<span class="st">'price_floz'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="split-into-training-and-test-dataframes" class="level2">
<h2 class="anchored" data-anchor-id="split-into-training-and-test-dataframes">Split into Training and Test DataFrames</h2>
<p>First, we will split our data into training and test DataFrames. 67% of observations will belong to the training DataFrame and the remaining 33% will go to the test DataFrame.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>dtrain, dtest <span class="op">=</span> df.randomSplit([<span class="fl">.67</span>, <span class="fl">.33</span>], seed <span class="op">=</span> <span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="overview-of-linear-regression-models" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-linear-regression-models">Overview of Linear Regression Models</h2>
<p>For the beer_markets DataFrame, we will consider and compare three different Linear Regression models. In Model 1, there are three independent or predictor variables: dummy variables for different beer markets, a dummy variable for whether or not the container is a can, and the log of the volume of beer in fluid ounces. Model 2 has the same independent variables as Model 1 in addition to the interaction term between different beer brands and the log of beer volume. Model 3 has the same independent variables as Model 2 in addition to three more interaction terms: whether or not promotion was used and the log of beer volume, brand and promotion usage, and brand, promotion usage, and the log of beer volume. For Models 2 and 3, the interaction terms show us how the relationship between one predictor and the outcome variable changes as the value of another predictor changes. For all three models, the dependent or outcome variable is the log of price per fluid ounce of beer. Using linear regression, we can predict the log price per fluid ounce based on the independent variables given in the model.</p>
</section>
<section id="training-the-models" class="level2">
<h2 class="anchored" data-anchor-id="training-the-models">Training the Models</h2>
<p>Before we begin training our models, we must add dummy variables for our categorical variables. To do this, we will apply our UDF for adding dummy variables. All observations must be numerical in order to train the Linear Regression Model.</p>
<div class="cell" data-outputid="23edf986-fbf8-4b10-ff51-713027c9e953" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>dummy_cols_brand, ref_category_brand <span class="op">=</span> add_dummy_variables(<span class="st">'brand'</span>, <span class="dv">0</span>, category_order<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dummy_cols_market, ref_category_market <span class="op">=</span> add_dummy_variables(<span class="st">'market'</span>, <span class="dv">5</span>, category_order<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>dummy_cols_container, ref_category_container <span class="op">=</span> add_dummy_variables(<span class="st">'container'</span>, <span class="dv">0</span>, category_order<span class="op">=</span><span class="va">None</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reference category (dummy omitted): BUD_LIGHT
Reference category (dummy omitted): BUFFALO-ROCHESTER
Reference category (dummy omitted): CAN</code></pre>
</div>
</div>
<section id="model-1" class="level3">
<h3 class="anchored" data-anchor-id="model-1">Model 1</h3>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>x_cols_1 <span class="op">=</span> [<span class="st">'log_beer_floz'</span>]</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>assembler_predictors_1 <span class="op">=</span> (</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    x_cols_1 <span class="op">+</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    dummy_cols_brand <span class="op">+</span> dummy_cols_market <span class="op">+</span> dummy_cols_container</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>assembler_1 <span class="op">=</span> VectorAssembler(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> assembler_predictors_1,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    outputCol <span class="op">=</span> <span class="st">"predictors"</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>dtrain_1 <span class="op">=</span> assembler_1.transform(dtrain)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>dtest_1  <span class="op">=</span> assembler_1.transform(dtest)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># training model</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>model_1 <span class="op">=</span> (</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        LinearRegression(featuresCol<span class="op">=</span><span class="st">"predictors"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>                                labelCol<span class="op">=</span><span class="st">"log_price_floz"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    .fit(dtrain_1)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># making prediction</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>dtrain_1 <span class="op">=</span> model_1.transform(dtrain_1)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>dtest_1 <span class="op">=</span> model_1.transform(dtest_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summary" class="level4">
<h4 class="anchored" data-anchor-id="summary">Summary</h4>
<div class="cell" data-outputid="bf5f8247-a631-4225-c821-5ce129a6b161" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dtest_1.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).show())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------+------------------+
|         prediction|        price_floz|
+-------------------+------------------+
| -2.792350778968452|0.0659027777777777|
| -2.864445041558655|0.0565277777777777|
|-2.8788697218373027|           0.06375|
|  -3.27220818906385|0.0392222222222222|
| -3.327091138288483|0.0388611111111111|
| -3.327091138288483|0.0388611111111111|
| -3.327091138288483|0.0415833333333333|
|-3.1275589685986342|0.0406944444444444|
| -2.766643192389631|0.0620833333333333|
|-2.7807239771704384|0.0740277777777777|
| -2.958268062960834|0.0485763888888888|
|-2.8454523724376664|0.0554861111111111|
|-2.8454523724376664|0.0763194444444444|
|-2.9003353216622996|           0.04625|
|-2.9003353216622996|           0.04625|
| -2.969479660376425|0.0444166666666666|
| -2.969479660376425|0.0471944444444444|
| -2.969479660376425|0.0471944444444444|
| -2.969479660376425|           0.05275|
| -2.890809854407121|0.0588888888888888|
+-------------------+------------------+
only showing top 20 rows

None</code></pre>
</div>
</div>
<div class="cell" data-outputid="819ede49-0fe1-47a2-d683-79e1cca7b066" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(regression_table(model_1, assembler_1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-----------------------------------+--------+------+------------+---------+--------------+--------------+
| Metric                            |  Value | Sig. | Std. Error | p-value | 95% CI Lower | 95% CI Upper |
+-----------------------------------+--------+------+------------+---------+--------------+--------------+
| Beta: log_beer_floz               | -0.135 | ***  |      0.003 |   0.000 |       -0.142 |       -0.129 |
| Beta: brand_BUSCH_LIGHT           | -0.265 | ***  |      0.003 |   0.000 |       -0.271 |       -0.259 |
| Beta: brand_COORS_LIGHT           | -0.004 |      |      0.003 |   0.224 |       -0.009 |        0.002 |
| Beta: brand_MILLER_LITE           | -0.017 | ***  |      0.003 |   0.000 |       -0.022 |       -0.011 |
| Beta: brand_NATURAL_LIGHT         | -0.320 | ***  |      0.014 |   0.000 |       -0.348 |       -0.293 |
| Beta: market_ALBANY               |  0.031 |  **  |      0.012 |   0.025 |        0.008 |        0.055 |
| Beta: market_ATLANTA              |  0.083 | ***  |      0.015 |   0.000 |        0.054 |        0.112 |
| Beta: market_BALTIMORE            |  0.098 | ***  |      0.012 |   0.000 |        0.075 |        0.122 |
| Beta: market_BIRMINGHAM           |  0.129 | ***  |      0.013 |   0.000 |        0.104 |        0.154 |
| Beta: market_BOSTON               |  0.122 | ***  |      0.012 |   0.000 |        0.099 |        0.145 |
| Beta: market_CHARLOTTE            |  0.016 |      |      0.011 |   0.173 |       -0.007 |        0.038 |
| Beta: market_CHICAGO              | -0.002 |      |      0.012 |   0.852 |       -0.025 |        0.021 |
| Beta: market_CINCINNATI           |  0.092 | ***  |      0.012 |   0.000 |        0.068 |        0.115 |
| Beta: market_CLEVELAND            |  0.061 | ***  |      0.011 |   0.000 |        0.039 |        0.083 |
| Beta: market_COLUMBUS             |  0.081 | ***  |      0.011 |   0.000 |        0.059 |        0.102 |
| Beta: market_DALLAS               |  0.208 | ***  |      0.013 |   0.000 |        0.182 |        0.234 |
| Beta: market_DENVER               |  0.116 | ***  |      0.013 |   0.000 |        0.091 |        0.142 |
| Beta: market_DES_MOINES           |  0.148 | ***  |      0.011 |   0.000 |        0.126 |        0.171 |
| Beta: market_DETROIT              |  0.098 | ***  |      0.031 |   0.000 |        0.037 |        0.159 |
| Beta: market_EXURBAN_NJ           |  0.141 | ***  |      0.029 |   0.000 |        0.085 |        0.198 |
| Beta: market_EXURBAN_NY           |  0.077 | ***  |      0.013 |   0.007 |        0.051 |        0.103 |
| Beta: market_GRAND_RAPIDS         |  0.088 | ***  |      0.017 |   0.000 |        0.055 |        0.120 |
| Beta: market_HARTFORD-NEW_HAVEN   |  0.129 | ***  |      0.011 |   0.000 |        0.106 |        0.151 |
| Beta: market_HOUSTON              |  0.115 | ***  |      0.012 |   0.000 |        0.091 |        0.139 |
| Beta: market_INDIANAPOLIS         |  0.095 | ***  |      0.016 |   0.000 |        0.064 |        0.127 |
| Beta: market_JACKSONVILLE         |  0.135 | ***  |      0.014 |   0.000 |        0.107 |        0.162 |
| Beta: market_KANSAS_CITY          |  0.071 | ***  |      0.015 |   0.000 |        0.041 |        0.101 |
| Beta: market_LITTLE_ROCK          |  0.101 | ***  |      0.011 |   0.000 |        0.079 |        0.123 |
| Beta: market_LOS_ANGELES          |  0.019 |      |      0.013 |   0.100 |       -0.008 |        0.045 |
| Beta: market_LOUISVILLE           |  0.075 | ***  |      0.015 |   0.000 |        0.045 |        0.105 |
| Beta: market_MEMPHIS              |  0.160 | ***  |      0.011 |   0.000 |        0.138 |        0.181 |
| Beta: market_MIAMI                |  0.107 | ***  |      0.013 |   0.000 |        0.082 |        0.132 |
| Beta: market_MILWAUKEE            |  0.038 | ***  |      0.013 |   0.003 |        0.013 |        0.063 |
| Beta: market_MINNEAPOLIS          |  0.131 | ***  |      0.013 |   0.000 |        0.106 |        0.156 |
| Beta: market_NASHVILLE            |  0.173 | ***  |      0.013 |   0.000 |        0.147 |        0.198 |
| Beta: market_NEW_ORLEANS-MOBILE   |  0.143 | ***  |      0.013 |   0.000 |        0.118 |        0.168 |
| Beta: market_OKLAHOMA_CITY-TULSA  |  0.159 | ***  |      0.012 |   0.000 |        0.135 |        0.183 |
| Beta: market_OMAHA                |  0.141 | ***  |      0.012 |   0.000 |        0.117 |        0.165 |
| Beta: market_ORLANDO              |  0.132 | ***  |      0.015 |   0.000 |        0.103 |        0.161 |
| Beta: market_PHILADELPHIA         |  0.096 | ***  |      0.011 |   0.000 |        0.074 |        0.118 |
| Beta: market_PHOENIX              |  0.154 | ***  |      0.016 |   0.000 |        0.122 |        0.186 |
| Beta: market_PITTSBURGH           |  0.088 | ***  |      0.014 |   0.000 |        0.061 |        0.116 |
| Beta: market_PORTLAND             |  0.104 | ***  |      0.012 |   0.000 |        0.080 |        0.128 |
| Beta: market_RALEIGH-DURHAM       |  0.094 | ***  |      0.012 |   0.000 |        0.070 |        0.119 |
| Beta: market_RICHMOND             |  0.029 |  **  |      0.017 |   0.018 |       -0.004 |        0.062 |
| Beta: market_RURAL_ALABAMA        |  0.165 | ***  |      0.020 |   0.000 |        0.125 |        0.204 |
| Beta: market_RURAL_ARKANSAS       |  0.178 | ***  |      0.013 |   0.000 |        0.153 |        0.203 |
| Beta: market_RURAL_CALIFORNIA     |  0.038 | ***  |      0.071 |   0.003 |       -0.101 |        0.177 |
| Beta: market_RURAL_COLORADO       |  0.171 |  **  |      0.014 |   0.016 |        0.143 |        0.198 |
| Beta: market_RURAL_FLORIDA        |  0.060 | ***  |      0.015 |   0.000 |        0.031 |        0.090 |
| Beta: market_RURAL_GEORGIA        |  0.151 | ***  |      0.020 |   0.000 |        0.111 |        0.190 |
| Beta: market_RURAL_IDAHO          |  0.172 | ***  |      0.012 |   0.000 |        0.149 |        0.196 |
| Beta: market_RURAL_ILLINOIS       |  0.016 |      |      0.015 |   0.196 |       -0.014 |        0.046 |
| Beta: market_RURAL_INDIANA        |  0.095 | ***  |      0.012 |   0.000 |        0.071 |        0.118 |
| Beta: market_RURAL_IOWA           |  0.090 | ***  |      0.021 |   0.000 |        0.048 |        0.132 |
| Beta: market_RURAL_KANSAS         |  0.108 | ***  |      0.019 |   0.000 |        0.070 |        0.146 |
| Beta: market_RURAL_KENTUCKY       |  0.152 | ***  |      0.016 |   0.000 |        0.121 |        0.183 |
| Beta: market_RURAL_LOUISIANA      |  0.115 | ***  |      0.016 |   0.000 |        0.084 |        0.146 |
| Beta: market_RURAL_MAINE          |  0.100 | ***  |      0.013 |   0.000 |        0.074 |        0.125 |
| Beta: market_RURAL_MICHIGAN       |  0.095 | ***  |      0.024 |   0.000 |        0.048 |        0.143 |
| Beta: market_RURAL_MINNESOTA      |  0.244 | ***  |      0.016 |   0.000 |        0.212 |        0.276 |
| Beta: market_RURAL_MISSISSIPPI    |  0.050 | ***  |      0.014 |   0.002 |        0.022 |        0.077 |
| Beta: market_RURAL_MISSOURI       |  0.105 | ***  |      0.016 |   0.000 |        0.074 |        0.137 |
| Beta: market_RURAL_MONTANA        |  0.114 | ***  |      0.024 |   0.000 |        0.066 |        0.162 |
| Beta: market_RURAL_NEBRASKA       |  0.169 | ***  |      0.014 |   0.000 |        0.141 |        0.197 |
| Beta: market_RURAL_NEVADA         |  0.038 | ***  |      0.044 |   0.007 |       -0.048 |        0.125 |
| Beta: market_RURAL_NEW_HAMPSHIRE  |  0.036 |      |      0.016 |   0.420 |        0.004 |        0.067 |
| Beta: market_RURAL_NEW_MEXICO     |  0.165 | ***  |      0.078 |   0.000 |        0.013 |        0.318 |
| Beta: market_RURAL_NEW_YORK       | -0.062 |      |      0.013 |   0.426 |       -0.087 |       -0.036 |
| Beta: market_RURAL_NORTH_CAROLINA |  0.007 |      |      0.024 |   0.613 |       -0.040 |        0.053 |
| Beta: market_RURAL_NORTH_DAKOTA   |  0.227 | ***  |      0.018 |   0.000 |        0.192 |        0.262 |
| Beta: market_RURAL_OHIO           |  0.098 | ***  |      0.037 |   0.000 |        0.027 |        0.170 |
| Beta: market_RURAL_OKLAHOMA       |  0.138 | ***  |      0.047 |   0.000 |        0.046 |        0.230 |
| Beta: market_RURAL_OREGON         |  0.036 |      |      0.016 |   0.447 |        0.005 |        0.066 |
| Beta: market_RURAL_PENNSYLVANIA   |  0.127 | ***  |      0.012 |   0.000 |        0.104 |        0.150 |
| Beta: market_RURAL_SOUTH_CAROLINA |  0.060 | ***  |      0.023 |   0.000 |        0.015 |        0.104 |
| Beta: market_RURAL_SOUTH_DAKOTA   |  0.072 | ***  |      0.016 |   0.002 |        0.041 |        0.103 |
| Beta: market_RURAL_TENNESSEE      |  0.192 | ***  |      0.011 |   0.000 |        0.170 |        0.215 |
| Beta: market_RURAL_TEXAS          |  0.173 | ***  |      0.022 |   0.000 |        0.130 |        0.216 |
| Beta: market_RURAL_VERMONT        |  0.092 | ***  |      0.020 |   0.000 |        0.053 |        0.130 |
| Beta: market_RURAL_VIRGINIA       |  0.013 |      |      0.016 |   0.494 |       -0.018 |        0.045 |
| Beta: market_RURAL_WASHINGTON     |  0.140 | ***  |      0.018 |   0.000 |        0.105 |        0.175 |
| Beta: market_RURAL_WEST_VIRGINIA  | -0.075 | ***  |      0.011 |   0.000 |       -0.098 |       -0.053 |
| Beta: market_RURAL_WISCONSIN      |  0.041 | ***  |      0.037 |   0.000 |       -0.032 |        0.114 |
| Beta: market_RURAL_WYOMING        |  0.157 | ***  |      0.012 |   0.000 |        0.133 |        0.181 |
| Beta: market_SACRAMENTO           |  0.016 |      |      0.018 |   0.192 |       -0.018 |        0.050 |
| Beta: market_SALT_LAKE_CITY       |  0.130 | ***  |      0.011 |   0.000 |        0.108 |        0.151 |
| Beta: market_SAN_ANTONIO          |  0.147 | ***  |      0.013 |   0.000 |        0.121 |        0.173 |
| Beta: market_SAN_DIEGO            | -0.003 |      |      0.012 |   0.821 |       -0.027 |        0.021 |
| Beta: market_SAN_FRANCISCO        |  0.078 | ***  |      0.013 |   0.000 |        0.054 |        0.103 |
| Beta: market_SEATTLE              |  0.106 | ***  |      0.012 |   0.000 |        0.083 |        0.129 |
| Beta: market_ST_LOUIS             |  0.015 |      |      0.015 |   0.202 |       -0.015 |        0.045 |
| Beta: market_SURBURBAN_NJ         | -0.046 | ***  |      0.015 |   0.002 |       -0.076 |       -0.016 |
| Beta: market_SURBURBAN_NY         |  0.090 | ***  |      0.017 |   0.000 |        0.057 |        0.123 |
| Beta: market_SYRACUSE             | -0.035 |  **  |      0.011 |   0.035 |       -0.056 |       -0.014 |
| Beta: market_TAMPA                |  0.116 | ***  |      0.013 |   0.000 |        0.091 |        0.141 |
| Beta: market_URBAN_NY             |  0.147 | ***  |      0.013 |   0.000 |        0.121 |        0.172 |
| Beta: market_WASHINGTON_DC        |  0.098 | ***  |      0.013 |   0.000 |        0.073 |        0.123 |
| Intercept                         | -2.207 | ***  |      0.001 |   0.000 |       -2.210 |       -2.205 |
----------------------------------------------------------------------------------------------------------
| Observations                      | 35,486 |      |            |         |              |              |
| R²                                |  0.511 |      |            |         |              |              |
| RMSE                              |  0.172 |      |            |         |              |              |
+-----------------------------------+--------+------+------------+---------+--------------+--------------+</code></pre>
</div>
</div>
</section>
</section>
<section id="model-2" class="level3">
<h3 class="anchored" data-anchor-id="model-2">Model 2</h3>
<p>We must add one more predictor to Model 2. We will add an interaction term between beer brand and log of beer volume.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>interaction_cols_brand_log_floz <span class="op">=</span> add_interaction_terms(dummy_cols_brand, [<span class="st">'log_beer_floz'</span>], var_list3<span class="op">=</span><span class="va">None</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>assembler_predictors_2 <span class="op">=</span> (</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    x_cols_1 <span class="op">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    dummy_cols_brand <span class="op">+</span> dummy_cols_market <span class="op">+</span> dummy_cols_container <span class="op">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    interaction_cols_brand_log_floz</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>assembler_2 <span class="op">=</span> VectorAssembler(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> assembler_predictors_2,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    outputCol <span class="op">=</span> <span class="st">"predictors"</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>dtrain_2 <span class="op">=</span> assembler_2.transform(dtrain)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>dtest_2  <span class="op">=</span> assembler_2.transform(dtest)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># training model</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>model_2 <span class="op">=</span> (</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>        LinearRegression(featuresCol<span class="op">=</span><span class="st">"predictors"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>                                labelCol<span class="op">=</span><span class="st">"log_price_floz"</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    .fit(dtrain_2)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># making prediction</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>dtrain_2 <span class="op">=</span> model_2.transform(dtrain_2)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>dtest_2 <span class="op">=</span> model_2.transform(dtest_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summary-1" class="level4">
<h4 class="anchored" data-anchor-id="summary-1">Summary</h4>
<div class="cell" data-outputid="d5401bb2-50dd-428e-e49b-427e8c6cb507" data-execution_count="20">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(regression_table(model_2, assembler_2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------------------------------+--------+------+------------+---------+--------------+--------------+
| Metric                                    |  Value | Sig. | Std. Error | p-value | 95% CI Lower | 95% CI Upper |
+-------------------------------------------+--------+------+------------+---------+--------------+--------------+
| Beta: log_beer_floz                       | -0.142 | ***  |      0.027 |   0.000 |       -0.195 |       -0.090 |
| Beta: brand_BUSCH_LIGHT                   | -0.146 | ***  |      0.024 |   0.000 |       -0.192 |       -0.100 |
| Beta: brand_COORS_LIGHT                   | -0.108 | ***  |      0.022 |   0.000 |       -0.150 |       -0.065 |
| Beta: brand_MILLER_LITE                   |  0.089 | ***  |      0.022 |   0.000 |        0.046 |        0.132 |
| Beta: brand_NATURAL_LIGHT                 | -0.581 | ***  |      0.014 |   0.000 |       -0.609 |       -0.554 |
| Beta: market_ALBANY                       |  0.034 |  **  |      0.012 |   0.015 |        0.010 |        0.057 |
| Beta: market_ATLANTA                      |  0.084 | ***  |      0.015 |   0.000 |        0.055 |        0.113 |
| Beta: market_BALTIMORE                    |  0.104 | ***  |      0.012 |   0.000 |        0.081 |        0.127 |
| Beta: market_BIRMINGHAM                   |  0.138 | ***  |      0.013 |   0.000 |        0.113 |        0.163 |
| Beta: market_BOSTON                       |  0.125 | ***  |      0.012 |   0.000 |        0.102 |        0.147 |
| Beta: market_CHARLOTTE                    |  0.012 |      |      0.011 |   0.294 |       -0.010 |        0.035 |
| Beta: market_CHICAGO                      | -0.006 |      |      0.012 |   0.607 |       -0.029 |        0.017 |
| Beta: market_CINCINNATI                   |  0.088 | ***  |      0.012 |   0.000 |        0.064 |        0.111 |
| Beta: market_CLEVELAND                    |  0.058 | ***  |      0.011 |   0.000 |        0.036 |        0.080 |
| Beta: market_COLUMBUS                     |  0.081 | ***  |      0.011 |   0.000 |        0.059 |        0.102 |
| Beta: market_DALLAS                       |  0.222 | ***  |      0.013 |   0.000 |        0.195 |        0.248 |
| Beta: market_DENVER                       |  0.116 | ***  |      0.013 |   0.000 |        0.091 |        0.141 |
| Beta: market_DES_MOINES                   |  0.144 | ***  |      0.011 |   0.000 |        0.122 |        0.166 |
| Beta: market_DETROIT                      |  0.098 | ***  |      0.031 |   0.000 |        0.037 |        0.158 |
| Beta: market_EXURBAN_NJ                   |  0.146 | ***  |      0.028 |   0.000 |        0.090 |        0.202 |
| Beta: market_EXURBAN_NY                   |  0.076 | ***  |      0.013 |   0.008 |        0.050 |        0.101 |
| Beta: market_GRAND_RAPIDS                 |  0.084 | ***  |      0.016 |   0.000 |        0.052 |        0.117 |
| Beta: market_HARTFORD-NEW_HAVEN           |  0.128 | ***  |      0.011 |   0.000 |        0.106 |        0.151 |
| Beta: market_HOUSTON                      |  0.115 | ***  |      0.012 |   0.000 |        0.091 |        0.139 |
| Beta: market_INDIANAPOLIS                 |  0.093 | ***  |      0.016 |   0.000 |        0.061 |        0.124 |
| Beta: market_JACKSONVILLE                 |  0.129 | ***  |      0.014 |   0.000 |        0.101 |        0.157 |
| Beta: market_KANSAS_CITY                  |  0.071 | ***  |      0.015 |   0.000 |        0.041 |        0.101 |
| Beta: market_LITTLE_ROCK                  |  0.101 | ***  |      0.011 |   0.000 |        0.078 |        0.123 |
| Beta: market_LOS_ANGELES                  |  0.012 |      |      0.013 |   0.275 |       -0.014 |        0.038 |
| Beta: market_LOUISVILLE                   |  0.072 | ***  |      0.015 |   0.000 |        0.043 |        0.102 |
| Beta: market_MEMPHIS                      |  0.161 | ***  |      0.011 |   0.000 |        0.139 |        0.182 |
| Beta: market_MIAMI                        |  0.109 | ***  |      0.013 |   0.000 |        0.084 |        0.134 |
| Beta: market_MILWAUKEE                    |  0.038 | ***  |      0.012 |   0.003 |        0.014 |        0.063 |
| Beta: market_MINNEAPOLIS                  |  0.134 | ***  |      0.013 |   0.000 |        0.109 |        0.159 |
| Beta: market_NASHVILLE                    |  0.176 | ***  |      0.013 |   0.000 |        0.150 |        0.201 |
| Beta: market_NEW_ORLEANS-MOBILE           |  0.135 | ***  |      0.013 |   0.000 |        0.110 |        0.160 |
| Beta: market_OKLAHOMA_CITY-TULSA          |  0.157 | ***  |      0.012 |   0.000 |        0.133 |        0.181 |
| Beta: market_OMAHA                        |  0.140 | ***  |      0.012 |   0.000 |        0.116 |        0.165 |
| Beta: market_ORLANDO                      |  0.132 | ***  |      0.015 |   0.000 |        0.103 |        0.162 |
| Beta: market_PHILADELPHIA                 |  0.095 | ***  |      0.011 |   0.000 |        0.073 |        0.117 |
| Beta: market_PHOENIX                      |  0.157 | ***  |      0.016 |   0.000 |        0.125 |        0.188 |
| Beta: market_PITTSBURGH                   |  0.086 | ***  |      0.014 |   0.000 |        0.059 |        0.114 |
| Beta: market_PORTLAND                     |  0.105 | ***  |      0.012 |   0.000 |        0.081 |        0.129 |
| Beta: market_RALEIGH-DURHAM               |  0.096 | ***  |      0.012 |   0.000 |        0.072 |        0.120 |
| Beta: market_RICHMOND                     |  0.029 |  **  |      0.017 |   0.020 |       -0.004 |        0.061 |
| Beta: market_RURAL_ALABAMA                |  0.166 | ***  |      0.020 |   0.000 |        0.127 |        0.205 |
| Beta: market_RURAL_ARKANSAS               |  0.187 | ***  |      0.013 |   0.000 |        0.162 |        0.212 |
| Beta: market_RURAL_CALIFORNIA             |  0.035 | ***  |      0.071 |   0.005 |       -0.103 |        0.174 |
| Beta: market_RURAL_COLORADO               |  0.171 |  **  |      0.014 |   0.015 |        0.144 |        0.199 |
| Beta: market_RURAL_FLORIDA                |  0.050 | ***  |      0.015 |   0.000 |        0.021 |        0.080 |
| Beta: market_RURAL_GEORGIA                |  0.147 | ***  |      0.020 |   0.000 |        0.107 |        0.186 |
| Beta: market_RURAL_IDAHO                  |  0.171 | ***  |      0.012 |   0.000 |        0.147 |        0.194 |
| Beta: market_RURAL_ILLINOIS               |  0.017 |      |      0.015 |   0.162 |       -0.013 |        0.047 |
| Beta: market_RURAL_INDIANA                |  0.105 | ***  |      0.012 |   0.000 |        0.082 |        0.129 |
| Beta: market_RURAL_IOWA                   |  0.092 | ***  |      0.021 |   0.000 |        0.051 |        0.134 |
| Beta: market_RURAL_KANSAS                 |  0.110 | ***  |      0.019 |   0.000 |        0.072 |        0.148 |
| Beta: market_RURAL_KENTUCKY               |  0.154 | ***  |      0.016 |   0.000 |        0.123 |        0.184 |
| Beta: market_RURAL_LOUISIANA              |  0.111 | ***  |      0.016 |   0.000 |        0.079 |        0.142 |
| Beta: market_RURAL_MAINE                  |  0.096 | ***  |      0.013 |   0.000 |        0.070 |        0.121 |
| Beta: market_RURAL_MICHIGAN               |  0.093 | ***  |      0.024 |   0.000 |        0.046 |        0.140 |
| Beta: market_RURAL_MINNESOTA              |  0.257 | ***  |      0.016 |   0.000 |        0.225 |        0.289 |
| Beta: market_RURAL_MISSISSIPPI            |  0.046 | ***  |      0.014 |   0.005 |        0.019 |        0.073 |
| Beta: market_RURAL_MISSOURI               |  0.109 | ***  |      0.016 |   0.000 |        0.078 |        0.141 |
| Beta: market_RURAL_MONTANA                |  0.114 | ***  |      0.024 |   0.000 |        0.066 |        0.161 |
| Beta: market_RURAL_NEBRASKA               |  0.170 | ***  |      0.014 |   0.000 |        0.143 |        0.198 |
| Beta: market_RURAL_NEVADA                 |  0.038 | ***  |      0.044 |   0.007 |       -0.048 |        0.125 |
| Beta: market_RURAL_NEW_HAMPSHIRE          |  0.031 |      |      0.016 |   0.481 |       -0.000 |        0.062 |
| Beta: market_RURAL_NEW_MEXICO             |  0.161 | ***  |      0.077 |   0.000 |        0.009 |        0.313 |
| Beta: market_RURAL_NEW_YORK               | -0.059 |      |      0.013 |   0.448 |       -0.084 |       -0.033 |
| Beta: market_RURAL_NORTH_CAROLINA         |  0.024 |  *   |      0.023 |   0.069 |       -0.022 |        0.070 |
| Beta: market_RURAL_NORTH_DAKOTA           |  0.231 | ***  |      0.018 |   0.000 |        0.196 |        0.266 |
| Beta: market_RURAL_OHIO                   |  0.100 | ***  |      0.036 |   0.000 |        0.028 |        0.171 |
| Beta: market_RURAL_OKLAHOMA               |  0.139 | ***  |      0.047 |   0.000 |        0.047 |        0.231 |
| Beta: market_RURAL_OREGON                 |  0.038 |      |      0.015 |   0.421 |        0.007 |        0.068 |
| Beta: market_RURAL_PENNSYLVANIA           |  0.127 | ***  |      0.012 |   0.000 |        0.104 |        0.149 |
| Beta: market_RURAL_SOUTH_CAROLINA         |  0.058 | ***  |      0.023 |   0.000 |        0.014 |        0.102 |
| Beta: market_RURAL_SOUTH_DAKOTA           |  0.071 | ***  |      0.016 |   0.002 |        0.041 |        0.102 |
| Beta: market_RURAL_TENNESSEE              |  0.194 | ***  |      0.011 |   0.000 |        0.172 |        0.217 |
| Beta: market_RURAL_TEXAS                  |  0.175 | ***  |      0.022 |   0.000 |        0.132 |        0.218 |
| Beta: market_RURAL_VERMONT                |  0.081 | ***  |      0.019 |   0.000 |        0.043 |        0.119 |
| Beta: market_RURAL_VIRGINIA               |  0.015 |      |      0.016 |   0.448 |       -0.017 |        0.046 |
| Beta: market_RURAL_WASHINGTON             |  0.141 | ***  |      0.018 |   0.000 |        0.106 |        0.176 |
| Beta: market_RURAL_WEST_VIRGINIA          | -0.074 | ***  |      0.011 |   0.000 |       -0.097 |       -0.052 |
| Beta: market_RURAL_WISCONSIN              |  0.040 | ***  |      0.037 |   0.000 |       -0.032 |        0.113 |
| Beta: market_RURAL_WYOMING                |  0.154 | ***  |      0.012 |   0.000 |        0.130 |        0.178 |
| Beta: market_SACRAMENTO                   |  0.014 |      |      0.017 |   0.235 |       -0.020 |        0.049 |
| Beta: market_SALT_LAKE_CITY               |  0.127 | ***  |      0.011 |   0.000 |        0.106 |        0.148 |
| Beta: market_SAN_ANTONIO                  |  0.143 | ***  |      0.013 |   0.000 |        0.117 |        0.169 |
| Beta: market_SAN_DIEGO                    | -0.005 |      |      0.012 |   0.703 |       -0.029 |        0.019 |
| Beta: market_SAN_FRANCISCO                |  0.077 | ***  |      0.013 |   0.000 |        0.053 |        0.102 |
| Beta: market_SEATTLE                      |  0.099 | ***  |      0.012 |   0.000 |        0.076 |        0.122 |
| Beta: market_ST_LOUIS                     |  0.014 |      |      0.015 |   0.215 |       -0.015 |        0.044 |
| Beta: market_SURBURBAN_NJ                 | -0.047 | ***  |      0.015 |   0.002 |       -0.077 |       -0.017 |
| Beta: market_SURBURBAN_NY                 |  0.087 | ***  |      0.017 |   0.000 |        0.054 |        0.120 |
| Beta: market_SYRACUSE                     | -0.040 |  **  |      0.011 |   0.015 |       -0.061 |       -0.020 |
| Beta: market_TAMPA                        |  0.114 | ***  |      0.013 |   0.000 |        0.088 |        0.139 |
| Beta: market_URBAN_NY                     |  0.149 | ***  |      0.013 |   0.000 |        0.123 |        0.174 |
| Beta: market_WASHINGTON_DC                |  0.095 | ***  |      0.005 |   0.000 |        0.086 |        0.105 |
| Beta: brand_BUSCH_LIGHT_*_log_beer_floz   | -0.021 | ***  |      0.004 |   0.000 |       -0.029 |       -0.013 |
| Beta: brand_COORS_LIGHT_*_log_beer_floz   |  0.019 | ***  |      0.004 |   0.000 |        0.011 |        0.027 |
| Beta: brand_MILLER_LITE_*_log_beer_floz   | -0.019 | ***  |      0.004 |   0.000 |       -0.027 |       -0.011 |
| Beta: brand_NATURAL_LIGHT_*_log_beer_floz |  0.048 | ***  |      0.018 |   0.000 |        0.012 |        0.083 |
| Intercept                                 | -2.169 | ***  |      0.003 |   0.000 |       -2.174 |       -2.163 |
------------------------------------------------------------------------------------------------------------------
| Observations                              | 35,486 |      |            |         |              |              |
| R²                                        |  0.516 |      |            |         |              |              |
| RMSE                                      |  0.171 |      |            |         |              |              |
+-------------------------------------------+--------+------+------------+---------+--------------+--------------+</code></pre>
</div>
</div>
<div class="cell" data-outputid="59dd7d09-3592-4d6a-8c33-50308d988223" data-execution_count="21">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dtest_2.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).show())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------+------------------+
|         prediction|        price_floz|
+-------------------+------------------+
|  -2.79184159063699|0.0659027777777777|
|-2.8594121622298223|0.0565277777777777|
| -2.869616423365115|           0.06375|
|-3.2968652189031418|0.0392222222222222|
|-3.3630798574977083|0.0388611111111111|
|-3.3630798574977083|0.0388611111111111|
|-3.3630798574977083|0.0415833333333333|
|-3.1358115955296135|0.0406944444444444|
| -2.760190593306609|0.0620833333333333|
|-2.7771575669310384|0.0740277777777777|
| -2.958054745817342|0.0485763888888888|
|-2.8540147644649227|0.0554861111111111|
|-2.8540147644649227|0.0763194444444444|
| -2.904018769588993|           0.04625|
| -2.904018769588993|           0.04625|
|-2.9670163656768107|0.0444166666666666|
|-2.9670163656768107|0.0471944444444444|
|-2.9670163656768107|0.0471944444444444|
|-2.9670163656768107|           0.05275|
| -2.891047126501169|0.0588888888888888|
+-------------------+------------------+
only showing top 20 rows

None</code></pre>
</div>
</div>
</section>
</section>
<section id="model-3" class="level3">
<h3 class="anchored" data-anchor-id="model-3">Model 3</h3>
<p>Similarly to Model 2, we must add more predictors for Model 3. Here, we will add a dummy variable for promotion and several more interaction terms. We will consider the interaction between bran and beer volume, promotion and beer volume, brand and promotion, and brand, promotion, and beer volume.</p>
<div class="cell" data-outputid="824ff438-3857-47dc-b742-3d253dc2bd55" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dummy_cols_promo, ref_category_promo <span class="op">=</span> add_dummy_variables(<span class="st">'promo'</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reference category (dummy omitted): False</code></pre>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>interaction_cols_brand_log_floz <span class="op">=</span> add_interaction_terms(dummy_cols_brand, [<span class="st">'log_beer_floz'</span>], var_list3<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>interaction_cols_promo_log_floz <span class="op">=</span> add_interaction_terms(dummy_cols_promo, [<span class="st">'log_beer_floz'</span>], var_list3<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>interaction_cols_brand_promo <span class="op">=</span> add_interaction_terms(dummy_cols_brand, dummy_cols_promo, var_list3<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>interaction_cols_brand_promo_log_floz <span class="op">=</span> add_interaction_terms(dummy_cols_brand, dummy_cols_promo, [<span class="st">'log_beer_floz'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>assembler_predictors_3 <span class="op">=</span> (</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>    x_cols_1 <span class="op">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    dummy_cols_brand <span class="op">+</span> dummy_cols_market <span class="op">+</span> dummy_cols_container <span class="op">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    interaction_cols_brand_log_floz <span class="op">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    interaction_cols_promo_log_floz <span class="op">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    interaction_cols_brand_promo <span class="op">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    interaction_cols_brand_promo_log_floz</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>assembler_3 <span class="op">=</span> VectorAssembler(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    inputCols <span class="op">=</span> assembler_predictors_3,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    outputCol <span class="op">=</span> <span class="st">"predictors"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>dtrain_3 <span class="op">=</span> assembler_3.transform(dtrain)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>dtest_3  <span class="op">=</span> assembler_3.transform(dtest)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># training model</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>model_3 <span class="op">=</span> (</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>        LinearRegression(featuresCol<span class="op">=</span><span class="st">"predictors"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>                                labelCol<span class="op">=</span><span class="st">"log_price_floz"</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    .fit(dtrain_3)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># making prediction</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>dtrain_3 <span class="op">=</span> model_3.transform(dtrain_3)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>dtest_3 <span class="op">=</span> model_3.transform(dtest_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="summary-2" class="level4">
<h4 class="anchored" data-anchor-id="summary-2">Summary</h4>
<div class="cell" data-outputid="9a137c43-afb2-4b2b-cc3a-fc687d4dbc8e" data-execution_count="26">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>beta_values <span class="op">=</span> model_3.coefficients.toArray()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> assembler_3.getInputCols()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>beta_table <span class="op">=</span> []</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(feature_names)):</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    beta_table.append([feature_names[i], beta_values[i]])</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>tabulate(beta_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>'------------------------------------------------  -----------\nlog_beer_floz                                     -0.136455\nbrand_BUSCH_LIGHT                                 -0.0907828\nbrand_COORS_LIGHT                                 -0.0737586\nbrand_MILLER_LITE                                  0.133081\nbrand_NATURAL_LIGHT                               -0.475828\nmarket_ALBANY                                      0.0253785\nmarket_ATLANTA                                     0.0763817\nmarket_BALTIMORE                                   0.0933113\nmarket_BIRMINGHAM                                  0.130783\nmarket_BOSTON                                      0.120143\nmarket_CHARLOTTE                                   0.0233496\nmarket_CHICAGO                                    -0.00188634\nmarket_CINCINNATI                                  0.0837354\nmarket_CLEVELAND                                   0.0522246\nmarket_COLUMBUS                                    0.0802702\nmarket_DALLAS                                      0.226722\nmarket_DENVER                                      0.129319\nmarket_DES_MOINES                                  0.135893\nmarket_DETROIT                                     0.0990648\nmarket_EXURBAN_NJ                                  0.13442\nmarket_EXURBAN_NY                                  0.0667537\nmarket_GRAND_RAPIDS                                0.0826997\nmarket_HARTFORD-NEW_HAVEN                          0.121944\nmarket_HOUSTON                                     0.115509\nmarket_INDIANAPOLIS                                0.0891036\nmarket_JACKSONVILLE                                0.130776\nmarket_KANSAS_CITY                                 0.0634972\nmarket_LITTLE_ROCK                                 0.097217\nmarket_LOS_ANGELES                                 0.0207496\nmarket_LOUISVILLE                                  0.0713703\nmarket_MEMPHIS                                     0.15059\nmarket_MIAMI                                       0.109035\nmarket_MILWAUKEE                                   0.0388026\nmarket_MINNEAPOLIS                                 0.127782\nmarket_NASHVILLE                                   0.176059\nmarket_NEW_ORLEANS-MOBILE                          0.126602\nmarket_OKLAHOMA_CITY-TULSA                         0.149795\nmarket_OMAHA                                       0.141953\nmarket_ORLANDO                                     0.135769\nmarket_PHILADELPHIA                                0.0831244\nmarket_PHOENIX                                     0.162801\nmarket_PITTSBURGH                                  0.0798706\nmarket_PORTLAND                                    0.106474\nmarket_RALEIGH-DURHAM                              0.0886988\nmarket_RICHMOND                                    0.0218335\nmarket_RURAL_ALABAMA                               0.162651\nmarket_RURAL_ARKANSAS                              0.178275\nmarket_RURAL_CALIFORNIA                            0.0341722\nmarket_RURAL_COLORADO                              0.178842\nmarket_RURAL_FLORIDA                               0.048985\nmarket_RURAL_GEORGIA                               0.140319\nmarket_RURAL_IDAHO                                 0.167423\nmarket_RURAL_ILLINOIS                              0.0143436\nmarket_RURAL_INDIANA                               0.104391\nmarket_RURAL_IOWA                                  0.0879043\nmarket_RURAL_KANSAS                                0.102565\nmarket_RURAL_KENTUCKY                              0.148982\nmarket_RURAL_LOUISIANA                             0.101282\nmarket_RURAL_MAINE                                 0.0952734\nmarket_RURAL_MICHIGAN                              0.0860976\nmarket_RURAL_MINNESOTA                             0.250628\nmarket_RURAL_MISSISSIPPI                           0.041842\nmarket_RURAL_MISSOURI                              0.100376\nmarket_RURAL_MONTANA                               0.125706\nmarket_RURAL_NEBRASKA                              0.166878\nmarket_RURAL_NEVADA                                0.0365143\nmarket_RURAL_NEW_HAMPSHIRE                         0.0245408\nmarket_RURAL_NEW_MEXICO                            0.151578\nmarket_RURAL_NEW_YORK                             -0.0721252\nmarket_RURAL_NORTH_CAROLINA                        0.0120202\nmarket_RURAL_NORTH_DAKOTA                          0.226628\nmarket_RURAL_OHIO                                  0.0947752\nmarket_RURAL_OKLAHOMA                              0.125907\nmarket_RURAL_OREGON                                0.0401582\nmarket_RURAL_PENNSYLVANIA                          0.116653\nmarket_RURAL_SOUTH_CAROLINA                        0.0593814\nmarket_RURAL_SOUTH_DAKOTA                          0.0652301\nmarket_RURAL_TENNESSEE                             0.205072\nmarket_RURAL_TEXAS                                 0.172253\nmarket_RURAL_VERMONT                               0.0837308\nmarket_RURAL_VIRGINIA                              0.00853721\nmarket_RURAL_WASHINGTON                            0.164909\nmarket_RURAL_WEST_VIRGINIA                        -0.0849587\nmarket_RURAL_WISCONSIN                             0.0389056\nmarket_RURAL_WYOMING                               0.147967\nmarket_SACRAMENTO                                  0.0217214\nmarket_SALT_LAKE_CITY                              0.124676\nmarket_SAN_ANTONIO                                 0.13696\nmarket_SAN_DIEGO                                  -0.0029509\nmarket_SAN_FRANCISCO                               0.0846383\nmarket_SEATTLE                                     0.110073\nmarket_ST_LOUIS                                    0.0168797\nmarket_SURBURBAN_NJ                               -0.0575105\nmarket_SURBURBAN_NY                                0.0850405\nmarket_SYRACUSE                                   -0.0509936\nmarket_TAMPA                                       0.113092\nmarket_URBAN_NY                                    0.143904\nmarket_WASHINGTON_DC                               0.0894661\nbrand_BUSCH_LIGHT_*_log_beer_floz                 -0.01597\nbrand_COORS_LIGHT_*_log_beer_floz                  0.00641913\nbrand_MILLER_LITE_*_log_beer_floz                 -0.0136419\nbrand_NATURAL_LIGHT_*_log_beer_floz                0.0139777\npromo_True_*_log_beer_floz                        -0.00484056\nbrand_BUSCH_LIGHT_*_promo_True                    -0.183267\nbrand_COORS_LIGHT_*_promo_True                    -0.118051\nbrand_MILLER_LITE_*_promo_True                    -0.198857\nbrand_NATURAL_LIGHT_*_promo_True                  -0.214949\nbrand_BUSCH_LIGHT_*_promo_True                    -0.183267\nbrand_COORS_LIGHT_*_promo_True                    -0.118051\nbrand_MILLER_LITE_*_promo_True                    -0.198857\nbrand_NATURAL_LIGHT_*_promo_True                  -0.214949\nbrand_BUSCH_LIGHT_*_log_beer_floz                 -0.01597\nbrand_COORS_LIGHT_*_log_beer_floz                  0.00641913\nbrand_MILLER_LITE_*_log_beer_floz                 -0.0136419\nbrand_NATURAL_LIGHT_*_log_beer_floz                0.0139777\npromo_True_*_log_beer_floz                        -0.00484056\nbrand_BUSCH_LIGHT_*_promo_True_*_log_beer_floz     0.067596\nbrand_COORS_LIGHT_*_promo_True_*_log_beer_floz     0.0411765\nbrand_MILLER_LITE_*_promo_True_*_log_beer_floz     0.071225\nbrand_NATURAL_LIGHT_*_promo_True_*_log_beer_floz   0.0779679\n------------------------------------------------  -----------'</code></pre>
</div>
</div>
<div class="cell" data-outputid="5717754b-2546-4404-a86a-3f3455295080" data-execution_count="27">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dtest_3.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).show())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------------+------------------+
|         prediction|        price_floz|
+-------------------+------------------+
| -2.783825132146986|0.0659027777777777|
| -2.852181232185633|0.0565277777777777|
|-2.8567168160602634|           0.06375|
|-3.2846580127148473|0.0392222222222222|
| -3.367438927218041|0.0388611111111111|
| -3.329453847087418|0.0388611111111111|
| -3.329453847087418|0.0415833333333333|
|-3.1540302069906416|0.0406944444444444|
|-2.7676073259050664|0.0620833333333333|
|-2.7590519598928407|0.0740277777777777|
| -3.001588386461357|0.0485763888888888|
|-2.9218829165297717|0.0554861111111111|
|-2.8423075221373013|0.0763194444444444|
|-2.9592348912579673|           0.04625|
|-2.9592348912579673|           0.04625|
|-3.0062928141417586|0.0444166666666666|
|-3.0062928141417586|0.0471944444444444|
|-3.0062928141417586|0.0471944444444444|
|-2.9555763843672302|           0.05275|
|-2.8847264383485465|0.0588888888888888|
+-------------------+------------------+
only showing top 20 rows

None</code></pre>
</div>
</div>
</section>
<section id="interpreting-beta-estimates-model-3" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-beta-estimates-model-3">Interpreting Beta Estimates (Model 3)</h4>
<ul>
<li>The beta value for market_ALBANY for Model 3 is 0.0253785.</li>
<li>The beta value for market_EXURBAN_NY is 0.0667537.</li>
<li>The beta value for market_RURAL_NEW_YORK is -0.0721252.</li>
<li>The beta value for market_SUBURBAN_NY is 0.0850405.</li>
<li>The beta value for market_SYRACUSE is -0.0509936.</li>
<li>The beta value for market_URBAN_NY is 0.143904.</li>
</ul>
<p>All of the above beta values for different beer markets from Model 3 are very close to zero. This suggests that the predictor variable, market, has little impact on the dependent or target variable, log price per fluid ounce.</p>
</section>
</section>
</section>
<section id="model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="model-comparison">Model Comparison</h2>
<section id="beta-estimates" class="level3">
<h3 class="anchored" data-anchor-id="beta-estimates">Beta Estimates</h3>
<p>The beta value for log beer volume in Model 1 is -0.135. The beta value for log beer volume from Model 2 is -0.142. The beta value from Model 3 is -0.136. All three beta values for log beer volume are between -1 and 0. This suggests price inelasticity, meaning a precentage change in log beer volume would lead to less than a percentage change in log beer price per fluid ounce. However, all three beta values are also very close to 0. This shows that the percentage change in beer price is relatively insenstive to a percentage change in beer volume.</p>
<p>The beta value for the interaction term between promo and log beer volume from Model 3 is -0.0048. This value is less negative than the beta value for log beer volume, suggesting that the use of promotion decreases price senstivity. In addition, this beta value is even closer to 0, meaning a change in beer volume leads to relatively no change in beer price while using promo.</p>
</section>
<section id="residual-plots" class="level3">
<h3 class="anchored" data-anchor-id="residual-plots">Residual Plots</h3>
<section id="model-1-1" class="level4">
<h4 class="anchored" data-anchor-id="model-1-1">Model 1</h4>
<div class="cell" data-outputid="001897e9-0c40-4156-a5b2-abe500810f27">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert test predictions to Pandas</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>dfpd_1 <span class="op">=</span> dtest_1.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).toPandas()</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>dfpd_1[<span class="st">"residual"</span>] <span class="op">=</span> dfpd_1[<span class="st">"price_floz"</span>] <span class="op">-</span> dfpd_1[<span class="st">"prediction"</span>]</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(dfpd_1[<span class="st">"prediction"</span>], dfpd_1[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lowess smoothing for the trend line</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(dfpd_1[<span class="st">"residual"</span>], dfpd_1[<span class="st">"prediction"</span>])</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted y (Model)"</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model"</span>)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hw3_part2_files/figure-html/cell-28-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>On the residual plot for Model 1, the residuals are centered around zero, meaning that on average, the predictions are correct. However, the plot shows some curvature, suggesting that there may be some systematic errors.</p>
</section>
<section id="model-2-1" class="level4">
<h4 class="anchored" data-anchor-id="model-2-1">Model 2</h4>
<div class="cell" data-outputid="4055e2df-6d6e-4504-ea4b-88cbb2106b91">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert test predictions to Pandas</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>dfpd_2 <span class="op">=</span> dtest_2.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).toPandas()</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>dfpd_2[<span class="st">"residual"</span>] <span class="op">=</span> dfpd_2[<span class="st">"price_floz"</span>] <span class="op">-</span> dfpd_2[<span class="st">"prediction"</span>]</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(dfpd_2[<span class="st">"prediction"</span>], dfpd_2[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lowess smoothing for the trend line</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(dfpd_2[<span class="st">"residual"</span>], dfpd_2[<span class="st">"prediction"</span>])</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted y (Model)"</span>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model"</span>)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hw3_part2_files/figure-html/cell-29-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>For Model 2, the residuals are centered around 0, like Model 1. This indicates that the model’s predictions are correct on average. The plot is curved but has less curvature than Model 1, showing that it may have less systematic errors.</p>
</section>
<section id="model-3-1" class="level4">
<h4 class="anchored" data-anchor-id="model-3-1">Model 3</h4>
<div class="cell" data-outputid="da2e9643-2825-4456-8e1d-9ba9f936b34c">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert test predictions to Pandas</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dfpd_3 <span class="op">=</span> dtest_3.select([<span class="st">"prediction"</span>, <span class="st">"price_floz"</span>]).toPandas()</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>dfpd_3[<span class="st">"residual"</span>] <span class="op">=</span> dfpd_3[<span class="st">"price_floz"</span>] <span class="op">-</span> dfpd_3[<span class="st">"prediction"</span>]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(dfpd_3[<span class="st">"prediction"</span>], dfpd_3[<span class="st">"residual"</span>], alpha<span class="op">=</span><span class="fl">0.2</span>, color<span class="op">=</span><span class="st">"darkgray"</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lowess smoothing for the trend line</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>smoothed <span class="op">=</span> sm.nonparametric.lowess(dfpd_3[<span class="st">"residual"</span>], dfpd_3[<span class="st">"prediction"</span>])</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.plot(smoothed[:, <span class="dv">0</span>], smoothed[:, <span class="dv">1</span>], color<span class="op">=</span><span class="st">"darkblue"</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">"red"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Predicted y (Model)"</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Residual Plot for Model"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="hw3_part2_files/figure-html/cell-30-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Like Models 1 and 2, the residuals for Model 3 are centered around 0. This shows that the model’s predictions are correct on average. The plot is slightly curved but has less curvature than Models 1 and 2, showing that it may have less systematic errors.</p>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>I prefer Model 3 because its residual plot shows the least amount of possible systematic errors with the predictions still being correct on average. However, the beta values for the beer markets are very close to 0, meaning that the market has little impact on the dependent variable. The market variable could be removed from this model and a different variable could be tested in its place.</p>


</section>

</main> <!-- /main -->
<script type="text/javascript" src="links.js"></script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">Powered with GitHub and Quarto<br>© Brennan, 2023</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>