project:
  type: website
  output-dir: "."

website:
  title: "Ann Brennan"
  navbar:
    pinned: true
    left:
      - text: DANL320 Final Project
        href: danl_320_brennan_ann_project.ipynb
      - text: Final Projects
        menu:
        - text: DANL200
          href: project.qmd
        - text: DANL210
          href: project-210.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Project
        href: danl_proj_nba.ipynb
      - text: Python Data Analysis
        menu: 
          - text: Pandas Basics
            href: pandas_basics.ipynb
          - text: Seaborn Basics
            href: seaborn_basics.ipynb
        
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Brennan, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html

 