project:
  type: website
  output-dir: "."

website:
  title: "Ann Brennan"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Python Data Analysis
        menu: 
          - text: Python Basics
          - href: python_basics_blog.ipynb
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Brennan, 2023"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html

 